image: node:latest

pages:
  script:
    - npm i -g yarn
    - yarn
    - yarn generate
  artifacts:
    paths:
      - dist
  cache:
    paths:
      - node_modules
    key: project
  only:
    - master
