image: node:latest

pages:
  script:
    - yarn
    - yarn generate
    - mv dist public
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
    key: project
  only:
    - master
