name: GitHub Pages deploy

on:
  push:
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
    - name: Install Yarn
      run: npm i -g yarn
    - name: Install dependencies
      run: yarn
    - name: Generate
      run: yarn generate
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v2.1.2
      with:
        target_branch: gh-pages
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.PAGES_DEPLOY }}
